// <auto-generated />
using System;
using EcoPulse.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoPulse.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117164143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcoPulse.Api.Models.Canje", b =>
                {
                    b.Property<int>("IdCanje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCanje"));

                    b.HasKey("IdCanje");

                    b.ToTable("Canjes");
                });

            modelBuilder.Entity("EcoPulse.Api.Models.CentroAcopio", b =>
                {
                    b.Property<int>("IdCentroAcopio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCentroAcopio"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HorarioAtencion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCentroAcopio");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("CentrosAcopio");
                });

            modelBuilder.Entity("EcoPulse.Api.Models.Comercio", b =>
                {
                    b.Property<int>("IdComercio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComercio"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdComercio");

                    b.ToTable("Comercios");
                });

            modelBuilder.Entity("EcoPulse.Api.Models.Entrega", b =>
                {
                    b.Property<int>("IdEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEntrega"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("double");

                    b.Property<int>("CentroAcopioIdCentroAcopio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCentroAcopio")
                        .HasColumnType("int");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("PuntosGenerados")
                        .HasColumnType("int");

                    b.HasKey("IdEntrega");

                    b.HasIndex("CentroAcopioIdCentroAcopio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("EcoPulse.Api.Models.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<string>("FactorPuntos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdMaterial");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("EcoPulse.Api.Models.Recompensa", b =>
                {
                    b.Property<int>("IdRecompensa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRecompensa"));

                    b.Property<int>("CostoPuntos")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdRecompensa");

                    b.ToTable("Recompensas");
                });

            modelBuilder.Entity("EcoPulse.Api.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PuntosTotales")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EcoPulse.Api.Models.CentroAcopio", b =>
                {
                    b.HasOne("EcoPulse.Api.Models.Usuario", "Usuario")
                        .WithOne("CentroAcopio")
                        .HasForeignKey("EcoPulse.Api.Models.CentroAcopio", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoPulse.Api.Models.Entrega", b =>
                {
                    b.HasOne("EcoPulse.Api.Models.CentroAcopio", "CentroAcopio")
                        .WithMany("Entregas")
                        .HasForeignKey("CentroAcopioIdCentroAcopio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoPulse.Api.Models.Usuario", "Usuario")
                        .WithMany("Entregas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroAcopio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoPulse.Api.Models.CentroAcopio", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("EcoPulse.Api.Models.Usuario", b =>
                {
                    b.Navigation("CentroAcopio")
                        .IsRequired();

                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
